# This is a basic workflow to help you get started with Actions

name: Build Lean project

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ automated ]
  pull_request:
    branches: [ automated ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Build Lean project"
  build_project:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    name: Build Lean project
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: automated
      
      - name: update branch
        if: github.ref == 'refs/heads/master'
        uses: leanprover-contrib/update-versions-action@master
      
      - name: build project
        uses: leanprover-contrib/lean-build-action@master
        # This is a basic workflow to help you get started with Actions
