name: Build LaTeX document
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
        
      - name: commit
        run: |
          git config user.name HanchaiN
          git config user.email 85230240+HanchaiN@users.noreply.github.com
          git add .
          git commit -m "generate `main.pdf`"
          git push
